name: my_supermarket_shopping_list
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  expandable_text: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/orrin.jpeg
    - clipboard-with-a-list.png
  fonts:
  - family: Courgette
    fonts:
    - asset: fonts/Courgette-Regular.ttf

  - family: SourceSansPro
    fonts:
    - asset: fonts/SourceSansPro-Regular.ttf